spring:
  data:
    mongodb:
      database: hotels
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vipinwebdev/microservice-config-server.git
          clone-on-start: true